### ISSUE TITLE
[hostmetricsreceiver][cpu] CPU scraper fails in Proxmox LXC with pinned non-sequential CPUs: "cannot find TimesStat for cpu"

### ISSUE THREAD

**Issue by TheKrizz** [open-telemetry/opentelemetry-collector-contrib#51131]
## Description
After upgrading from otelcol-contrib 0.160.0 to 0.161.0, the hostmetrics CPU scraper started logging the following error repeatedly:

```
error scraperhelper@v0.161.0/obs_metrics.go:61 Error scraping metrics
{"scraper":"cpu","error":"getting time for cpu cpu2: cpu cpu2 : cannot find TimesStat for cpu"}
```

Inside the container, /proc/cpuinfo exposes CPUs numbered from 0 to 3:
```
grep '^processor' /proc/cpuinfo
processor       : 0
processor       : 1
processor       : 2
processor       : 3
```

However, /proc/stat exposes CPU statistics using the original host CPU IDs:
```
grep '^cpu[0-9]' /proc/stat | awk '{print $1}'
cpu5
cpu23
cpu26
cpu41
```

Addition information:
```
nproc
4
```

```
taskset -pc $$
pid 30030's current affinity list: 5,23,26,41
```

```
grep Cpus_allowed_list /proc/self/status
Cpus_allowed_list:      5,23,26,41
```

```
cat /sys/fs/cgroup/cpuset.cpus.effective
5,23,26,41
````

## Steps to Reproduce
The issue is reproducible on a Proxmox LXC container.
The same container configuration works correctly with otelcol-contrib 0.160.0 and does not produce any CPU scraper errors.

## Expected Result
The CPU scraper should handle LXC environments where:

cpuset-restricted CPUs are non-sequential
/proc/cpuinfo and /proc/stat expose different CPU numbering schemes

or at least gracefully skip mismatched CPUs without producing scraper errors.

### Collector version

0.161.0

## Environment
otelcol-contrib version 0.161.0
Virtualization: LXC (Proxmox)
Kernel: Linux 7.0.0-3-pve
Architecture: x86_64
OS: 24.04.5 LTS (Noble Numbat)

### OpenTelemetry Collector configuration

```yaml
host_metrics/system:
    collection_interval: 30s
    initial_delay: 1s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
      processes:
      system:
```

### Log output

```shell
Sep 17 15:27:51 HOSTNAME otelcol-contrib[5298]: 2026-09-17T15:27:51.276+0200        error        scraperhelper@v0.161.0/obs_metrics.go:61        Error scraping metrics        {"resource": {"service.instance.id": "175db99c-cb22-4056-bf96-074633612ecb", "service.name": "otelcol-contrib", "service.version": "0.161.0"}, "otelcol.component.id": "host_metrics/system", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics", "scraper": "cpu", "error": "getting time for cpu cpu2: cpu cpu2 : cannot find TimesStat for cpu"}
Sep 17 15:27:51 HOSTNAME otelcol-contrib[5298]: go.opentelemetry.io/collector/scraper/scraperhelper.wrapObsMetrics.func1
Sep 17 15:27:51 HOSTNAME otelcol-contrib[5298]:         go.opentelemetry.io/collector/scraper/scraperhelper@v0.161.0/obs_metrics.go:61
Sep 17 15:27:51 HOSTNAME otelcol-contrib[5298]: go.opentelemetry.io/collector/scraper.ScrapeMetricsFunc.ScrapeMetrics
Sep 17 15:27:51 HOSTNAME otelcol-contrib[5298]:         go.opentelemetry.io/collector/scraper@v0.161.0/metrics.go:24
Sep 17 15:27:51 HOSTNAME otelcol-contrib[5298]: go.opentelemetry.io/collector/scraper/scraperhelper.scrapeMetrics
Sep 17 15:27:51 HOSTNAME otelcol-contrib[5298]:         go.opentelemetry.io/collector/scraper/scraperhelper@v0.161.0/controller.go:155
Sep 17 15:27:51 HOSTNAME otelcol-contrib[5298]: go.opentelemetry.io/collector/scraper/scraperhelper.NewMetricsController.func1
Sep 17 15:27:51 HOSTNAME otelcol-contrib[5298]:         go.opentelemetry.io/collector/scraper/scraperhelper@v0.161.0/controller.go:125
Sep 17 15:27:51 HOSTNAME otelcol-contrib[5298]: go.opentelemetry.io/collector/scraper/scraperhelper/internal/controller.(*Controller[...]).startScraping.func1
Sep 17 15:27:51 HOSTNAME otelcol-contrib[5298]:         go.opentelemetry.io/collector/scraper/scraperhelper@v0.161.0/internal/controller/controller.go:124
Sep 17 15:27:51 HOSTNAME otelcol-contrib[5298]: sync.(*WaitGroup).Go.func1
Sep 17 15:27:51 HOSTNAME otelcol-contrib[5298]:         sync/waitgroup.go:258
```

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

**Comment by TheKrizz** [comment]
It is currently unclear whether this is a regression in otelcol-contrib or an environment-specific issue.

A restart of the otelcol-contrib process appears to resolve the error, at least temporarily. I will continue monitoring the affected systems to determine whether the issue reoccurs.

The affected systems are nightly-build LXC containers running on Proxmox and provisioned automatically using OpenTofu. If the issue occurs again, I will provide additional logs and diagnostics.

**Comment by braydonk** [comment]
We rely on the [gopsutil](https://github.com/shirou/gopsutil) library for collecting the CPU time stats and we inherit whatever behaviour they decide on. In a scenario where `/proc/stat` doesn't line up with `/proc/cpuinfo`, I'm actually not sure what `gopsutil` should be expected to do, but you could open an issue with them suggesting a remediation strategy if you have a thought.

As for the scraper, I feel like us producing an error in the case where we're unable to reconcile the CPU times for a given logical cpu number is actually the right thing to do. I'm not sure users would want a failure like that swallowed in most cases.
