### ISSUE TITLE
Cannot build `GOOS=windows GOARCH=arm64`

### ISSUE THREAD

**Issue by braydonk** [open-telemetry/opentelemetry-collector-contrib#40247]
## Description

There appears to be a build-tag definition problem of some kind with `windows arm64` builds, and I think it started in v0.126.0.

## Steps to Reproduce

```shell
make genotelcontribcol
cd ./cmd/otelcontribcol
GOWORK=off GOOS=windows GOARCH=arm64 go build .
# github.com/DataDog/gohai/cpu
../../../../go/pkg/mod/github.com/!data!dog/gohai@v0.0.0-20230524154621-4316413895ee/cpu/cpu_windows.go:270:15: undefined: computeCoresAndProcessors
# github.com/DataDog/gohai/platform
../../../../go/pkg/mod/github.com/!data!dog/gohai@v0.0.0-20230524154621-4316413895ee/platform/platform_windows.go:168:29: undefined: SERVER_INFO_101
../../../../go/pkg/mod/github.com/!data!dog/gohai@v0.0.0-20230524154621-4316413895ee/platform/platform_windows.go:185:9: undefined: platGetServerInfo
# github.com/DataDog/datadog-agent/pkg/util/winutil
../../../../go/pkg/mod/github.com/!data!dog/datadog-agent/pkg/util/winutil@v0.66.0-devel.0.20250407180930-ebfcfa2817ce/winmem.go:126:15: undefined: performanceInformation
# github.com/open-telemetry/opentelemetry-collector-contrib/pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters
../../pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/pdh.go:347:89: undefined: PDH_FMT_COUNTERVALUE_DOUBLE
../../pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/pdh.go:515:77: undefined: PDH_RAW_COUNTER
../../pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/performance_query.go:127:12: undefined: PDH_COUNTER_INFO
../../pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/performance_query.go:137:12: undefined: PDH_FMT_COUNTERVALUE_DOUBLE
../../pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/performance_query.go:160:28: undefined: PDH_FMT_COUNTERVALUE_ITEM_DOUBLE
../../pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/performance_query.go:176:15: undefined: PDH_RAW_COUNTER
../../pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/performance_query.go:199:28: undefined: PDH_RAW_COUNTER_ITEM
```

## Expected Result

Successful Windows ARM64 build.

## Actual Result

Posted in repro steps.

### Collector version

`main`

## Environment
OS: Appears unimportant; this leverages Go cross-compile features.
Compiler(if manually compiled): `go1.24.3`

### OpenTelemetry Collector configuration

```yaml
N/A
```

### Log output

```shell
Posted in repro steps.
```

**Comment by braydonk** [comment]
I went back as far as `v0.123.0` and also tried with `go1.23.9` and this is still happening. I swear this has worked for me before 🤔

**Comment by mx-psi** [comment]
If you are up for being an owner of this platform we can add it as [Tier 3 supported platform](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/platform-support.md#tier-3---community-support) and add some cross compilation tests to core and contrib to make sure it is buildable

**Comment by braydonk** [comment]
I didn't realize this wasn't an already supported platform; I thought it used to work so opened the issue when I saw it wasn't working. But if it's not even a supported platform then this is fine.

I'll leave this open as a general Windows ARM64 build issue. I don't think I have any particular requirement for it any time soon so I'm not willing to commit to any ownership at this time, but if that changes I might be able to. I'll leave this open for now either way.

**Comment by pjanotti** [comment]
Eventually we'll need to get Windows ARM64 build support, but, I didn't start to look at it yet - the demand has being tiny AFAIK.

**Comment by pjanotti** [comment]
@braydonk ah thanks, missed that.

**Comment by pjanotti** [comment]
Hi @songy23 - could you please help add support for `arm64` to the DataDog packages? Here is the set of failures after #41658

```terminal
# github.com/DataDog/datadog-agent/pkg/util/winutil
/Users/pjanotti/go/pkg/mod/github.com/!data!dog/datadog-agent/pkg/util/winutil@v0.67.0/winmem.go:126:15: undefined: performanceInformation
# github.com/DataDog/gohai/cpu
/Users/pjanotti/go/pkg/mod/github.com/!data!dog/gohai@v0.0.0-20230524154621-4316413895ee/cpu/cpu_windows.go:270:15: undefined: computeCoresAndProcessors
# github.com/DataDog/gohai/platform
/Users/pjanotti/go/pkg/mod/github.com/!data!dog/gohai@v0.0.0-20230524154621-4316413895ee/platform/platform_windows.go:168:29: undefined: SERVER_INFO_101
/Users/pjanotti/go/pkg/mod/github.com/!data!dog/gohai@v0.0.0-20230524154621-4316413895ee/platform/platform_windows.go:185:9: undefined: platGetServerInfo
```

**Comment by pjanotti** [comment]
@braydonk 
>  I thought it used to work so opened the issue when I saw it wasn't working

It probably did work in the past, but then we added dependencies dependent on CPU architecture.

**Comment by songy23** [comment]
@pjanotti do you have a link to the failure in http://github.com/open-telemetry/opentelemetry-collector-contrib/issues/40247#issuecomment-3133532827?

**Comment by pjanotti** [comment]
No @songy23, this is local, you can use the steps from the initial description to repro it locally. When we have the Windows ARM build fixed I will add it to CI and later publish via release.

**Comment by songy23** [comment]
For both `datadog-agent/pkg/util/winutil` and `datadog/gohai/platform/platform_windows`, it seems only 386 and amd64 are supported, arm64 is not supported. They may need a go build tag !arm64

cc @mx-psi probably knows gohai better than me

**Comment by mx-psi** [comment]
For `pkg/util/winutil` it seems like we just need to add a file like https://github.com/DataDog/datadog-agent/blob/main/pkg/util/winutil/winmem_amd64.go but for `arm64`, which based on https://learn.microsoft.com/en-us/windows/win32/api/psapi/ns-psapi-performance_information it's probably going to be the exact same as the amd64 file. @pjanotti could you confirm this? I am happy to do a PR in the Agent if you confirm that using the same definition as in amd64 would work

Gohai I think we can just do #41695

**Comment by songy23** [comment]
> it's probably going to be the exact same as the amd64 file.

That seems exactly what https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/41658/files was doing. cc @pjanotti

**Comment by pjanotti** [comment]
As @songy23 pointed, the amd64 and arm64 should be the same.

**Comment by mx-psi** [comment]
Cool, filed DataDog/datadog-agent/pull/39427 on the Agent repo

**Comment by mx-psi** [comment]
This is fixed upstream, @songy23 do you think that it is safe to pin a pseudoversion for `pkg/util/winutil` or should we wait until the next Agent release?

**Comment by songy23** [comment]
pseudoversion would be great, the new version of agent pkg/trace introduces some deadlock (I didn't have time to look closer) so we cannot upgrade all the agent packages for now

**Comment by mx-psi** [comment]
With #41731, I am able to build for `windows/arm64` 🎉:

```
❯ GOOS=windows GOARCH=arm64 make otelcontribcol
./internal/buildscripts/ocb-add-replaces.sh otelcontribcol
Wrote replace statements to cmd/otelcontribcol/builder-config-replaced.yaml
/home/pablo.baeyens/Source/otel/opentelemetry-collector-contrib/.tools/builder --skip-compilation --config cmd/otelcontribcol/builder-config-replaced.yaml
2025-08-01T17:47:35.768+0200    INFO    internal/command.go:98  OpenTelemetry Collector Builder {"version": "v0.131.0"}
2025-08-01T17:47:35.769+0200    INFO    internal/command.go:103 Using config file       {"path": "cmd/otelcontribcol/builder-config-replaced.yaml"}
2025-08-01T17:47:35.781+0200    INFO    builder/config.go:160   Using go        {"go-executable": "/home/pablo.baeyens/.gvm/gos/go1.23.4/bin/go"}
2025-08-01T17:47:35.811+0200    INFO    builder/main.go:99      Sources created {"path": "./cmd/otelcontribcol"}
2025-08-01T17:47:37.284+0200    INFO    builder/main.go:200     Getting go modules
2025-08-01T17:47:37.652+0200    INFO    builder/main.go:106     Generating source codes only, the distribution will not be compiled.
cd ./cmd/otelcontribcol && GO111MODULE=on CGO_ENABLED=0 go build -trimpath -o ../../bin/otelcontribcol_windows_arm64.exe \
        -tags "" .

```

**Comment by mx-psi** [comment]
@braydonk Should we close this, or do you want to add CI tests to prevent regressions as part of this issue?

**Comment by pjanotti** [comment]
@mx-psi @braydonk I will look into adding a very basic smoke test so we ensure no regression here.
