### ISSUE TITLE
govulncheck (extension) fails on all PRs: cockroachdb/swiss does not build with Go 1.27

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-collector-contrib#50382]
#### Component(s)

extension/pebble_tail_storage

#### Describe the issue you're reporting

The `govulncheck (extension)` CI job fails on every PR since 2026-08-20, when `actions/setup-go` started resolving `stable` to the newly released Go 1.27.0.

The failure is in `extension/tailstorage/pebbletailstorageextension`, which depends on `github.com/cockroachdb/swiss` (indirect, via `cockroachdb/pebble/v2`). swiss defines `hashFn`, `getRuntimeHasher`, and `fastrand64` in files gated by Go version build tags that cap at go1.26, so the package does not build with Go 1.27:

```
/home/runner/go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:286:7: undefined: hashFn
/home/runner/go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:337:14: undefined: getRuntimeHasher
/home/runner/go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:338:22: undefined: fastrand64
```

It surfaces on every PR through govulncheck because that job sweeps all modules with `go-version: stable`, while the unittest shards are ci-scoped to changed modules. The extension will fail to build under Go 1.27 in any job that compiles it with the stable toolchain.

Example failing runs (unrelated PRs, same error):

- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/32349470001/job/96366008845 (#50353)
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/32354258108 (#48017)

Upstream state: cockroachdb/swiss#51 tracks the Go 1.27 build failure and cockroachdb/swiss#52 is an open fix. The currently pinned commit (`b0f6560`, 2025-12-24) is the latest on swiss main, so there is no version to bump to yet.

Options until upstream merges:

- pin the govulncheck job to `oldstable` so PRs are unblocked
- bump swiss (via a pebble bump or a temporary `replace`) once cockroachdb/swiss#52 merges

I'm happy to open the workflow pin PR.

**Comment by paulojmdias** [comment]
I think this should be kept open to revert the pin later?
