### ISSUE TITLE
Upgrade k8s.io/client-go to 0.28.1

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#26024]
k8s.io/client-go/tools/leaderelection/resourcelock got a breaking change introduced in https://github.com/kubernetes/client-go/commit/27bbe765353fa01ed516b11bde1da82ae6f6c3bc. We need to adopt the code to upgrade the library. Otherwise, it's not compiling

```
# github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver/internal/k8sapiserver
Error: ../../receiver/awscontainerinsightreceiver/internal/k8sapiserver/k8sapiserver.go:222:16: undefined: resourcelock.ConfigMapsLeasesResourceLock

```
