### PR TITLE
[chore] Upgrade k8s.io/client-go to v0.28.1

### LINKED ISSUE #26024: Upgrade k8s.io/client-go to 0.28.1
k8s.io/client-go/tools/leaderelection/resourcelock got a breaking change introduced in https://github.com/kubernetes/client-go/commit/27bbe765353fa01ed516b11bde1da82ae6f6c3bc. We need to adopt the code to upgrade the library. Otherwise, it's not compiling

```
# github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver/internal/k8sapiserver
Error: ../../receiver/awscontainerinsightreceiver/internal/k8sapiserver/k8sapiserver.go:222:16: undefined: resourcelock.ConfigMapsLeasesResourceLock

```

### PR DESCRIPTION
**Pull request by crobert-1**
**Description:** <Describe what has changed.>

There was a breaking change in this upgrade that needed to be handled manually. The fix is to replace usages of ConfigMapsLeasesResourceLock with LeasesResourceLock.

To do the deps updates I did the following:
``` 
cd internal/aws/k8s/
go get -u k8s.io/client-go@v0.28.1
cd ../../kubelet/
go get -u k8s.io/client-go@v0.28.1
```
These directories correspond to the two PRs that were closed because of the original issue.
Original PRs: #26010, and #26156.

This doesn't update all packages to use v0.28.1, so let me know if I should update to include all others as well.

**Link to tracking Issue:** <Issue number if applicable>
Fixes #26024

**Testing:** <Describe what testing was performed and which tests were added.>
Build completes successfully now

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by TylerHelmuth — COMMENTED** [review]
@crobert-1 are there any release notes or changelog instructions that point us to `LeasesResourceLock` with the removal of `ConfigMapsLeasesResourceLock`?

**Review by atoulme — APPROVED** [review]

**Comment by crobert-1** [comment]
> @crobert-1 are there any release notes or changelog instructions that point us to `LeasesResourceLock` with the removal of `ConfigMapsLeasesResourceLock`?

The source is the PR introducing the original change:
https://github.com/kubernetes/kubernetes/pull/117558

From the PR:
```
client-go: the leader election library no longer supports leader-election locks for `endpointsleases` or `configmapsleases` resources. Users of those lock resources should move to `leases` which is safe to do in a single release.```

**Review by bryan-aguilar — APPROVED** [review]

**Review by TylerHelmuth — APPROVED** [review]

**Comment by jinja2** [comment]
To summarize the impact of this change, `k8s.io/client-go v0.28.0` drops support for using `ConfigMapLeases` for leader-elections [upstream PR](https://github.com/kubernetes/kubernetes/pull/117558). We are switching the receiver which supports leader-election to use only `Leases` object as opposed to the current behavior of using `ConfigMaps` and `Leases` both (which was an intermediary step to make switching from configmap to leases non-breaking). When a user upgrades their daemonset/deployments, the new client will use lease for election, while the old client which has been using both the lease and configmap will still be able to participate. One thing to note though there is no cleanup of the configmap after all clients have been upgraded to use the lease object. The team could potentially drop [these](https://github.com/aws-observability/aws-otel-collector/blob/main/deployment-template/eks/otel-container-insights-infra.yaml#L41-%23L44) permissions if interested.

**Comment by bryan-aguilar** [comment]
Ty for the summary @jinja2. I've sent this to the rest of the ADOT team and we will take a look at those permissions after these changes are shipped.
