### PR TITLE
Fix build for go 1.13

### LINKED ISSUE #47: Fix build for go 1.13
Attempting to build this repo with go 1.13 currently fails. Here is the output of `make test`:
```
$ make test
go: directory receiver/zipkinscribereceiver is outside main module
go test -race -timeout 30s 
build .: cannot find module for path .
make: *** [test] Error 1
```
It appears the behavior of `go list` in go 1.13 is different. It prints the warning "outside main module" which then causes the problem when makefile attempts to parse that output.

Tested on Mac OS X, `go1.13 darwin/amd64`

-------

Likely caused by https://github.com/golang/go/commit/b9edee32e15eb2ea66fe96563088520fff6f2535

-------

Possible solution is to exclude nested modules from ALL_SRC variable in makefile. However this will also remove them from `make test` target. To bring back testing of components in nested modules we can call `make test` in component subdirectories.

This will probably also require merging test coverage results into one report.

### PR DESCRIPTION
**Pull request by rghetia**
fixes #47

The fix runs the tests in subdirectories. I had also added a merge script to merge the raw reports and convert it to html. This works except when a new module is added. It fails because the coverage tool tries to fetch the latest version of the new module from github and it doesn't exists. 
Here is the error I get
```
go tool cover -html=coverage.txt -o coverage.html
cover: no matching versions for query "latest"
make: *** [test-with-cover] Error 1
```
As a result, I removed the merge script. Reports are in each sub-directories.

This also fixes the [issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/41#pullrequestreview-331601644) of not running the test for new modules in CI.

### CODE REVIEW

**Review by pjanotti — APPROVED** [review]
Thanks @rghetia, LGTM.

**Review by tigrannajaryan — APPROVED** [review]
@rghetia thank you!

Can you please add an issue to look into the coverage merging problem in the future? It would be nice to see everything in one html, so that you don't have to open each individually. Not a dealbreaker, though.

Just to double check: this now works both with go 1.12 and 1.13 or we require go 1.13?

Nit: please capitalize commit message.

**Review by owais — APPROVED** [review]

**Comment by rghetia** [comment]
> @rghetia thank you!
> 
> Can you please add an issue to look into the coverage merging problem in the future? It would be nice to see everything in one html, so that you don't have to open each individually. Not a dealbreaker, though.
> 
opened #67 

> Just to double check: this now works both with go 1.12 and 1.13 or we require go 1.13?

I ran `make ci` using 1.12 and  1.13 on top of master and on top of #41 
current CI uses 1.12 as well.

> 
> Nit: please capitalize commit message.
fixed.

**Comment by owais** [comment]
_Installing Go 1.13_
