### PR TITLE
[extension/jaegerremotesampling]: Replace Thrift-gen with Proto-gen types for sampling strategies

### LINKED ISSUE #18401: Bump github.com/jaegertracing/jaeger from 1.41.0 to 1.42.0 causes issues
### Component(s)

extension/jaegerremotesampling

## Description

Updating the dependency from 1.41.0 to 1.42.0 causes the following error in the test because of the change in using `api_v2.SamplingStrategyResponse` from `sampling.SamplingStrategyResponse`:

```
--- FAIL: TestEndpointsAreWired (0.01s)
    --- FAIL: TestEndpointsAreWired/new (0.00s)
        http_test.go:86: 
                Error Trace:    /Users/alex.boten/workspace/opentelemetry-collector-contrib/extension/jaegerremotesampling/internal/http_test.go:86
                Error:          Not equal: 
                                expected: "{\"strategyType\":\"PROBABILISTIC\"}"
                                actual  : "{}"
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -{"strategyType":"PROBABILISTIC"}
                                +{}
                Test:           TestEndpointsAreWired/new
FAIL
FAIL    github.com/open-telemetry/opentelemetry-collector-contrib/extension/jaegerremotesampling/internal       10.753s
FAIL
```

The strategyType field in the api_v2 is not rendered because of the `omitempty` tag in the struct. What's the right way to address this in the extension? 

See the PR here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18400

### Collector version

not-released-yet

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by frzifus**
**Description:** <Describe what has changed.>

Replace Thrift-gen with Proto-gen types for sampling strategies. This change breaks existing clients.

Do we have to take this into account and first inform the users a few releases ahead?
It seems to be a bit more effort to support both formats over a few releases and then deprecate thrift.

wdyt?
 
**Link to tracking Issue:** <Issue number if applicable>
Closes #18401 
Ref #18047

--

cc @jpkrohling

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
In general breaking changes are done through the use of a feature gate first.

- first release: Starting with the gate as an opt-in with a warning of the deprecation for the breaking change,
- second release: changing the gate to be an opt-out and changing the default behaviour to the new one
- third release: finally removing the gate

**Comment by frzifus** [comment]
Ups - I thought that was already done. I will look into it.

File: extension/jaegerremotesampling/internal/http_test.go [hunk 1]
```diff
@@ -13,7 +13,7 @@ import (
 	"net/url"
 	"testing"
 
-	"github.com/jaegertracing/jaeger/thrift-gen/sampling"
+	"github.com/jaegertracing/jaeger/proto-gen/api_v2"
```
Comment (frzifus) [inline extension/jaegerremotesampling/internal/http_test.go:16]: I assume it does make sense to keep both implementations for now and add something like a feature flag to enable it? wdyt @codeboten @jpkrohling

Comment (codeboten) [reply extension/jaegerremotesampling/internal/http_test.go:16]: Makes sense to me 👍🏻

Comment (codeboten) [reply extension/jaegerremotesampling/internal/http_test.go:16]: Support enabling the new implementation via feature flag first, then make it the default on the following version, then remove the ability to use the old implementation in the next version before removing the old implementation altogether

**Comment by frzifus** [comment]
lets continue here once https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24414 is done.

File: extension/jaegerremotesampling/internal/http_test.go (hunk 1 above)
Comment (frzifus) [reply extension/jaegerremotesampling/internal/http_test.go:16]: Any idea how to make the feature flag work without coping the entire protobuf definition from v1.41.0?

**Comment by zcross** [comment]
> This change breaks existing clients.

Can you help me understand this a little? gRPC client interactions, using binary encoded protobufs, should be unaffected right? Based on the diff I see in some tests, it seems like the breaking change here is for clients who use JSON encoded equivalents to the protos, in particular for some enum values?

File: .chloggen/jaegerremotesampling_replace_thrift-gen_with_proto-gen.yaml [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: Replace Thrift-gen with Proto-gen types for sampling strategies
+
+# One or more tracking issues related to the change
+issues: [18401]
+
+# (Optional) One or more lines of additional information to render under the primary note.
+# These lines will be padded with 2 spaces and then inserted directly into the document.
+# Use pipe (|) for multiline entries.
+subtext:
```
Comment (zcross) [inline .chloggen/jaegerremotesampling_replace_thrift-gen_with_proto-gen.yaml:16]: Can you explain the details of the change being `breaking` in the subtext? How are current clients impacted? 
Most importantly (to me, selfishly), what does this mean for _OTEL_ JaegerRemoteSampler implementations (more so than for Jaeger agents)?

Comment (zcross) [reply .chloggen/jaegerremotesampling_replace_thrift-gen_with_proto-gen.yaml:16]: (Hopefully the breakage is limited to JSON client interactions and not at all impacting binary encoded proto requests i.e., gRPC?)

File: extension/jaegerremotesampling/extension.go [hunk 3]
```diff
@@ -48,14 +48,15 @@ func (jrse *jrsExtension) Start(ctx context.Context, host component.Host) error
...
 		}
-		ss, err := static.NewStrategyStore(opts, jrse.telemetry.Logger)
-		if err != nil {
-			return fmt.Errorf("failed to create the local file strategy store: %w", err)
-		}
-
-		// there's a Close function on the concrete type, which is not visible to us...
-		// how can we close it then?
-		jrse.samplingStore = ss
+		_ = opts
```
Comment (zcross) [inline extension/jaegerremotesampling/extension.go:51]: unintentional to commit these commented lines?

File: extension/jaegerremotesampling/factory.go [hunk 4]
```diff
@@ -40,6 +43,14 @@ func createDefaultConfig() component.Config {
 	}
 }
 
+var once sync.Once
+
+func logDeprecation(logger *zap.Logger) {
+	once.Do(func() {
+		logger.Warn("jaegerremotesampling extension will replace Thrift-gen with Proto-gen to be compatbible to jaeger 1.42.0 and higher. See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18485 for more details.")
```
Comment (zcross) [inline extension/jaegerremotesampling/factory.go:50]: Nice.

File: extension/jaegerremotesampling/internal/http_test.go [hunk 5]
```diff
@@ -72,7 +72,10 @@ func TestEndpointsAreWired(t *testing.T) {
 			resp.Body.Close()
 
 			body := string(samplingStrategiesBytes)
-			assert.Equal(t, `{"strategyType":"PROBABILISTIC"}`, body)
```
Comment (zcross) [inline extension/jaegerremotesampling/internal/http_test.go:75]: Does the type enum field even matter any more?

See https://github.com/jaegertracing/jaeger-idl/blob/main/proto/api_v2/sampling.proto#L97

> Legacy field that was meant to indicate which one of the strategy fields
> below is present. This enum was not extended when per-operation strategy
> was introduced, because extending enum has backwards compatiblity issues.
> The recommended approach for consumers is to ignore this field and instead
> checks the other fields being not null (starting with operationSampling).
> For producers, it is recommended to set this field correctly for probabilistic
> and rate-limiting strategies, but if per-operation strategy is returned,
> the enum can be set to 0 (probabilistic).

File: extension/jaegerremotesampling/internal/internal_test.go [hunk 6]
```diff
@@ -6,16 +6,19 @@ package internal
...
 }
 
-func (m *mockCfgMgr) GetSamplingStrategy(ctx context.Context, serviceName string) (*sampling.SamplingStrategyResponse, error) {
+func (m *mockCfgMgr[T]) GetSamplingStrategy(ctx context.Context, serviceName string) (T, error) {
 	if m.getSamplingStrategyFunc != nil {
-		return m.getSamplingStrategyFunc(ctx, serviceName)
+		return m.getSamplingStrategyFunc[T](ctx, serviceName)
 	}
-	return sampling.NewSamplingStrategyResponse(), nil
+	return new(T), nil
```
Comment (zcross) [inline extension/jaegerremotesampling/internal/internal_test.go:20]: unintentional comment commit / WIP?

File: .chloggen/jaegerremotesampling_replace_thrift-gen_with_proto-gen.yaml [hunk 7]
```diff
@@ -0,0 +1,16 @@
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: breaking
+
+# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
+component: jaegerremotesampling
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: Replace Thrift-gen with Proto-gen types for sampling strategies
```
Comment (MovieStoreGuy) [inline .chloggen/jaegerremotesampling_replace_thrift-gen_with_proto-gen.yaml:8]: What do you see as the user facing change?

File: extension/jaegerremotesampling/extension.go (hunk 3 above)
Comment (MovieStoreGuy) [inline extension/jaegerremotesampling/extension.go:51]: Please don't commit commented out code, it makes it hard to maintain the code base.

File: extension/jaegerremotesampling/internal/http_test.go (hunk 1 above)
Comment (MovieStoreGuy) [reply extension/jaegerremotesampling/internal/http_test.go:16]: Is it possible to use a replace statement to lock the version to the breaking version changes, and then within the next release(s) follow the feature gate rollout and then remove the replace?

**Review by MovieStoreGuy — COMMENTED** [review]
Looks like a few things that need to be updated, let us know if pinning versions here will help with the rollout.

**Comment by zcross** [comment]
Would it be possible (with support? I'm willing to help) to try and get this landed ahead of next Monday's `0.83.0` release? My primary motivation as a user of this extension is knowing that it is compatible with _OTEL_ implementations of JaegerRemoteSampler, and not just Jaeger implementations. I left a few questions alluding to that, and otherwise don't really have any nitpicks to leave (I care more about the ends than the means).

On that note, no rush and the release date doesn't really matter to me if OTEL implementations are actually fine in the status quo (however, I see that the golang implementation actually takes the thrift-vs-proto enum encoding issue into account and is thankfully compatible with either encoding format0.

File: extension/jaegerremotesampling/internal/http_test.go (hunk 1 above)
Comment (frzifus) [reply extension/jaegerremotesampling/internal/http_test.go:16]: From my understanding no. Since the interface changes with the version bump. I think the easierst way would be to move the entire extension into a `deprecated` subfolder and put the feature flag into the factory. Its not nice, but since stuff gets removed soon..

File: .chloggen/jaegerremotesampling_replace_thrift-gen_with_proto-gen.yaml (hunk 7 above)
Comment (frzifus) [reply .chloggen/jaegerremotesampling_replace_thrift-gen_with_proto-gen.yaml:8]: The grpc interface will change. The returned values do not match.

**Comment by frzifus** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25126

Thats what I had in mind - wdyt? @zcross @MovieStoreGuy

**Comment by zcross** [comment]
> #25126
> 
> Thats what I had in mind - wdyt? @zcross @MovieStoreGuy

Honestly, if integration tests pass, everything compiles, and people using the extension can pick between using the proto or thrift variants, I don't have any objections. I'm not totally up to speed on how we do feature flagging in the project so I lack much intuition. The deprecation package rename scares me a little bit but it doesn't really matter to me if it's just a part of migration and the extension is still usable during (and of course after) the migration.

**Comment by zcross** [comment]
BTW: @frzifus if want any help validating this once it's merged, let me know. I have already been "dogfooding" my recent change via dev images and have a good working setup that uses the extension + `remote` source.

**Comment by frzifus** [comment]
> Honestly, if integration tests pass, everything compiles, and people using the extension can pick between using the proto or thrift variants, I don't have any objections. I'm not totally up to speed on how we do feature flagging in the project so I lack much intuition. The deprecation package rename scares me a little bit but it doesn't really matter to me if it's just a part of migration and the extension is still usable during (and of course after) the migration.

Ok, nice - if it makes it into v0.83.0 it should defently be removed in v0.87.0. 

> BTW: @frzifus if want any help validating this once it's merged, let me know. I have already been "dogfooding" my recent change via dev images and have a good working setup that uses the extension + remote source in coordination with the OTEL golang JaegerRemoteSampler implementation.

That would be great thx :)

File: extension/jaegerremotesampling/internal/http_test.go (hunk 1 above)
Comment (MovieStoreGuy) [reply extension/jaegerremotesampling/internal/http_test.go:16]: I don't see any other approach that would help here, just need to deprecated package doesn't down grade the version used in the main component.

**Comment by MovieStoreGuy** [comment]
I will review the changes in detail in my morning.

File: .chloggen/jaegerremotesampling_replace_thrift-gen_with_proto-gen.yaml [hunk 8]
```diff
@@ -0,0 +1,16 @@
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: breaking
```
Comment (atoulme) [inline .chloggen/jaegerremotesampling_replace_thrift-gen_with_proto-gen.yaml:2]: you can update the changelog to indicate this is an api breaking change.

Comment (frzifus) [reply .chloggen/jaegerremotesampling_replace_thrift-gen_with_proto-gen.yaml:2]: Using this approach it will just add a featuregate for the next releases. I assume it will be removed / a breaking change then in ~0.87.0, right?

**Comment by ericashi** [comment]
Hi,

Can we have a rough timeline (eg: 1week, 2weeks, 1month, etc) on when this can be solved, please?
We saw this vulnerability and wanted to know when it can be addressed to estimate when we can use Opentelemetry in our company development environment.

Thank you.

Best Regards,
Erica Ooi

**Comment by ericashi** [comment]
> Hi,
> 
> Can we have a rough timeline (eg: 1week, 2weeks, 1month, etc) on when this can be solved, please? We saw this vulnerability and wanted to know when it can be addressed to estimate when we can use Opentelemetry in our company development environment.
> 
> Thank you.
> 
> Best Regards, Erica Ooi

Hi,

May I follow up on this question, please?

Thank you.

Best Regards,
Erica Ooi

**Comment by ericashi** [comment]
> > Hi,
> > Can we have a rough timeline (eg: 1week, 2weeks, 1month, etc) on when this can be solved, please? We saw this vulnerability and wanted to know when it can be addressed to estimate when we can use Opentelemetry in our company development environment.
> > Thank you.
> > Best Regards, Erica Ooi
> 
> Hi,
> 
> May I follow up on this question, please?
> 
> Thank you.
> 
> Best Regards, Erica Ooi

Hi,

I see no reply for my question yet. 
May I follow up again on this question, please?

Thank you.

Best Regards, 
Erica Ooi

**Comment by jpkrohling** [comment]
We do not embed the Jaeger UI in any form within the Collector. Therefore, the report you are seeing is a false-positive. If your business still needs this fixed, I recommend forking this component, fixing it, and building your distribution based on your fork. It would certainly be appreciated if you could contribute back the fix, but it's not required.

Despite our best intentions, we cannot give timelines or promises on when the Jaeger version will be bumped.

**Comment by frzifus** [comment]
> Can we have a rough timeline (eg: 1week, 2weeks, 1month, etc) on when this can be solved, please?

Hi @ericashi, yes - I hope to reslove this by the end of this week. As of this morning, I am fully operational again.

thanks @zcross, let me come back to you soon.

**Comment by ericashi** [comment]
> > Can we have a rough timeline (eg: 1week, 2weeks, 1month, etc) on when this can be solved, please?
> 
> Hi @ericashi, yes - I hope to reslove this by the end of this week. As of this morning, I am fully operational again.
> 
> thanks @zcross, let me come back to you soon. Btw I would like to stick to this approach:
> 
> * [[extension/Jaegerremotesampling] replace thrift gen with proto gen #25126](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25126)
> 
> But I will update this PR and close the other.

Hi @frzifus ,

Thank you for stepping up to resolve this.
Looking forward for your good news soon as this is a gating point for our company to adopt Opentelemetry if this vulnerability is not resolve.

Thank you.

Best Regards,
Erica Ooi

File: .chloggen/jaegerremotesampling_replace_thrift-gen_with_proto-gen.yaml [hunk 9]
```diff
@@ -0,0 +1,19 @@
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: enhancement
+
+# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
+component: jaegerreceiver,jaegerremotesamplingextension
```
Comment (frzifus) [inline .chloggen/jaegerremotesampling_replace_thrift-gen_with_proto-gen.yaml:5]: After adding a featuregate to the `jaegerremotesamplingextension` the module worked fine, but it was not possible to compile the contrib client. Since otelcontribcol used 1.48.

<details>
<summary>Log</summary>

```
cd ./cmd/otelcontribcol && GO111MODULE=on CGO_ENABLED=0 go build -trimpath -o ../../bin/otelcontribcol_linux_amd64 \
	-tags "" .
# github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver
../../receiver/jaegerreceiver/trace_receiver.go:174:43: cannot use (*notImplementedConfigManager)(nil) (value of type *notImplementedConfigManager) as configmanager.ClientConfigManager value in variable declaration: *notImplementedConfigManager does not implement configmanager.ClientConfigManager (wrong type for method GetSamplingStrategy)
		have GetSamplingStrategy(context.Context, string) (*"github.com/jaegertracing/jaeger/thrift-gen/sampling".SamplingStrategyResponse, error)
		want GetSamplingStrategy(context.Context, string) (*api_v2.SamplingStrategyResponse, error)
../../receiver/jaegerreceiver/trace_receiver.go:281:74: cannot use &notImplementedConfigManager{} (value of type *notImplementedConfigManager) as configmanager.ClientConfigManager value in argument to httpserver.NewHTTPServer: *notImplementedConfigManager does not implement configmanager.ClientConfigManager (wrong type for method GetSamplingStrategy)
		have GetSamplingStrategy(context.Context, string) (*"github.com/jaegertracing/jaeger/thrift-gen/sampling".SamplingStrategyResponse, error)
		want GetSamplingStrategy(context.Context, string) (*api_v2.SamplingStrategyResponse, error)
# github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/zipkin/zipkinv1
../../pkg/translator/zipkin/zipkinv1/thrift.go:27:47: not enough arguments in call to jaegerzipkin.DeserializeThrift
	have ([]byte)
	want (context.Context, []byte)
make: *** [Makefile:287: otelcontribcol] Fehler 1
```
</details>

Therefore, I have increased the version there the same way and provided another [feature gate](https://github.com/open-telemetry/opentelemetry-collector/blob/26c150c8bee385184d26669701560f99245bb16d/featuregate/README.md). They work independently of each other.

Comment (frzifus) [reply .chloggen/jaegerremotesampling_replace_thrift-gen_with_proto-gen.yaml:5]: cc @jpkrohling @zcross @MovieStoreGuy

**Review by jpkrohling — APPROVED** [review]

**Comment by ericashi** [comment]
Hi @frzifus ,

May I follow up on this vulnerability, please?
Is it resolved?

Thank you.

Best Regards,
Erica Ooi

File: extension/jaegerremotesampling/jaegerremotesamplingdeprecated/internal/sampling/strategystore/factory.go [hunk 10]
```diff
@@ -0,0 +1,36 @@
+// Copyright (c) 2018 The Jaeger Authors.
```
Comment (codeboten) [inline extension/jaegerremotesampling/jaegerremotesamplingdeprecated/internal/sampling/strategystore/factory.go:1]: I know it's only temporary but should the copied files should include the otel license at the top?

File: receiver/jaegerreceiver/jaegerreceiverdeprecated/metadata.yaml [hunk 11]
```diff
@@ -0,0 +1,17 @@
+type: jaeger
```
Comment (codeboten) [inline receiver/jaegerreceiver/jaegerreceiverdeprecated/metadata.yaml:1]: don't think you'll need the metadata files in the deprecated components that aren't modules

**Review by codeboten — COMMENTED** [review]
Could the `*deprecated` copies be made internal to the modules that still need them? And is there a clear indication as to when those will be removed?

File: extension/jaegerremotesampling/jaegerremotesamplingdeprecated/internal/sampling/strategystore/factory.go (hunk 10 above)
Comment (frzifus) [reply extension/jaegerremotesampling/jaegerremotesamplingdeprecated/internal/sampling/strategystore/factory.go:1]: Would they be added on top? Meaning that there would be otel + jaeger? Or how does it work?

**Comment by ericashi** [comment]
> @ericashi as @jpkrohling pointed out, this might not belong to this PR: [#18485 (comment)](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18485#issuecomment-1689396275)
> 
> fyi: This PR will bump the jaeger dependencies to v1.48. But still use v1.41 as basis for the next 3 releases. There will be two new feature flags you can use to only run the 1.48 code, if enabled.

Hi @frzifus ,

Does this mean that the github dependabot check will still flag this vulnerability after this updates has been released in v0.84.0 - v0.86.0?
May I know what is the process to escalate this so that it can be fix earlier, with condition that I am unable to do the fix myself as I am first time user of this system that I am not familiar of the system and codes yet to be able to contribute right away?

Thank you.

Best Regards,
Erica Ooi

File: extension/jaegerremotesampling/jaegerremotesamplingdeprecated/internal/sampling/strategystore/factory.go (hunk 10 above)
Comment (jpkrohling) [reply extension/jaegerremotesampling/jaegerremotesamplingdeprecated/internal/sampling/strategystore/factory.go:1]: You can't remove the copyright from the original, but you can add ours to it, in case we do changes here.

Comment (frzifus) [reply extension/jaegerremotesampling/jaegerremotesamplingdeprecated/internal/sampling/strategystore/factory.go:1]: There are no changes planned. I hope it simply gets removed in the upcoming releases.

**Comment by frzifus** [comment]
@codeboten I moved the `*deprecated` packages into an internal one. There is now also a readme pointing to this PR. Linting should be fixed.

**Comment by jpkrohling** [comment]
Once @codeboten approves, this is ready to be merged.

**Review by codeboten — COMMENTED** [review]
This is looking really close, just a couple of questions

File: extension/jaegerremotesampling/internal/http_test.go (hunk 5 above)
Comment (frzifus) [reply extension/jaegerremotesampling/internal/http_test.go:75]: I think you are correct. Its no longer needed. I changed the test to verify a given `ProbabilisticSampling` field.

File: receiver/jaegerreceiver/factory.go [hunk 12]
```diff
@@ -39,8 +42,30 @@ var disableJaegerReceiverRemoteSampling = featuregate.GlobalRegistry().MustRegis
...
+	featuregate.StageBeta,
+	featuregate.WithRegisterDescription(
+		"When enabled, the jaegerreceiver will use Proto-gen over Thrift-gen.",
+	),
+)
+
 // NewFactory creates a new Jaeger receiver factory.
 func NewFactory() receiver.Factory {
+	if !protoGate.IsEnabled() {
+		jaegerreceiverdeprecated.NewFactory()
```
[the remark this answers is not in the document]
Comment (frzifus) [reply receiver/jaegerreceiver/factory.go:67]: ups, seems like that was a rebase issue, thanks!

**Comment by frzifus** [comment]
@codeboten should be fixed. Is there something else missing? :)

**Review by codeboten — APPROVED** [review]
Thanks @frzifus

**Comment by zcross** [comment]
@frzifus 

I'm trying to use this locally (flipping on and off the feature gate) and I keep seeing the warning message about upcoming deprecation. 

Does that mean that I'm:
1. Simply specifying the command name incorrectly?
2. Running into https://github.com/open-telemetry/opentelemetry-collector/issues/4967 which suggests that CLI-specified feature gate settings are not necessarily visible to component factories due to a race condition?

**Comment by mx-psi** [comment]
@zcross Thanks for reporting this, would you mind opening a separate issue for this?

**Comment by frzifus** [comment]
@zcross the warning will always be printed. But... :face_exhaling: 

Something is defiantly wrong. :/ Adding a `fmt.Println(protoGate.IsEnabled())` and running the following command multiple times shows different results. 

```bash
./bin/otelcontribcol_linux_amd64 --config=config.yaml --feature-gates=+extension.jaegerremotesampling.replaceThriftWithProto
```

What wonders me even more. Because in the generated main file, the factories of all existing components are created first and then **afterwards** the CLI commands are evaluated.

**Comment by davispuh** [comment]
In logs I see this

> {"level":"warn","ts":1729291563.3518195,"caller":"jaegerreceiver@v0.111.0/factory.go:49","msg":"jaeger receiver will deprecate Thrift-gen and replace it with Proto-gen to be compatbible to jaeger 1.42.0 and higher. See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18485 for more details.","kind":"receiver","name":"jaeger","data_type":"traces"}

How do I switch to the new behavior (`Proto-gen`) so that it doesn't output this warning?

My current config is like this:
```
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268
```

**Comment by mx-psi** [comment]
@davispuh Would you mind filing a separate issue for this?

**Comment by davispuh** [comment]
Okay I created #35894
