### ISSUE TITLE
Fix build for go 1.13

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#47]
Attempting to build this repo with go 1.13 currently fails. Here is the output of `make test`:
```
$ make test
go: directory receiver/zipkinscribereceiver is outside main module
go test -race -timeout 30s 
build .: cannot find module for path .
make: *** [test] Error 1
```
It appears the behavior of `go list` in go 1.13 is different. It prints the warning "outside main module" which then causes the problem when makefile attempts to parse that output.

Tested on Mac OS X, `go1.13 darwin/amd64`

-------

Likely caused by https://github.com/golang/go/commit/b9edee32e15eb2ea66fe96563088520fff6f2535

-------

Possible solution is to exclude nested modules from ALL_SRC variable in makefile. However this will also remove them from `make test` target. To bring back testing of components in nested modules we can call `make test` in component subdirectories.

This will probably also require merging test coverage results into one report.
