### PR TITLE
[chore] Add smoke build for Windows arm64

### LINKED ISSUE #40247: Cannot build `GOOS=windows GOARCH=arm64`
### Component(s)

_No response_

## Description

There appears to be a build-tag definition problem of some kind with `windows arm64` builds, and I think it started in v0.126.0.

## Steps to Reproduce

```shell
make genotelcontribcol
cd ./cmd/otelcontribcol
GOWORK=off GOOS=windows GOARCH=arm64 go build .
# github.com/DataDog/gohai/cpu
../../../../go/pkg/mod/github.com/!data!dog/gohai@v0.0.0-20230524154621-4316413895ee/cpu/cpu_windows.go:270:15: undefined: computeCoresAndProcessors
# github.com/DataDog/gohai/platform
../../../../go/pkg/mod/github.com/!data!dog/gohai@v0.0.0-20230524154621-4316413895ee/platform/platform_windows.go:168:29: undefined: SERVER_INFO_101
../../../../go/pkg/mod/github.com/!data!dog/gohai@v0.0.0-20230524154621-4316413895ee/platform/platform_windows.go:185:9: undefined: platGetServerInfo
# github.com/DataDog/datadog-agent/pkg/util/winutil
../../../../go/pkg/mod/github.com/!data!dog/datadog-agent/pkg/util/winutil@v0.66.0-devel.0.20250407180930-ebfcfa2817ce/winmem.go:126:15: undefined: performanceInformation
# github.com/open-telemetry/opentelemetry-collector-contrib/pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters
../../pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/pdh.go:347:89: undefined: PDH_FMT_COUNTERVALUE_DOUBLE
../../pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/pdh.go:515:77: undefined: PDH_RAW_COUNTER
../../pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/performance_query.go:127:12: undefined: PDH_COUNTER_INFO
../../pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/performance_query.go:137:12: undefined: PDH_FMT_COUNTERVALUE_DOUBLE
../../pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/performance_query.go:160:28: undefined: PDH_FMT_COUNTERVALUE_ITEM_DOUBLE
../../pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/performance_query.go:176:15: undefined: PDH_RAW_COUNTER
../../pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/performance_query.go:199:28: undefined: PDH_RAW_COUNTER_ITEM
```

## Expected Result

Successful Windows ARM64 build.

## Actual Result

Posted in repro steps.

### Collector version

`main`

## Environment
OS: Appears unimportant; this leverages Go cross-compile features.
Compiler(if manually compiled): `go1.24.3`

### OpenTelemetry Collector configuration

```yaml
N/A
```

### Log output

```shell
Posted in repro steps.
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pjanotti**
Adds a smoke build for Windows arm64, the goal here is to detect any regressions to the work done in #40247. End to end tests already have similar steps but initially adding same build steps to `build-and-test-windows.yml` while I will evaluate the status of the group tests on Windows arm64. If the tests are not noisey we can add the `windows-11-arm` runner to the group tests and `scoped-tests`.

Fix #40247

### CODE REVIEW

**Review by songy23 — APPROVED** [review]

**Review by atoulme — APPROVED** [review]

**Comment by songy23** [comment]
It's working http://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/16889920528/job/47848283227?pr=41885

govuln checks are a known bug http://github.com/golang/vulndb/issues/3860

**Comment by pjanotti** [comment]
Link back to https://github.com/open-telemetry/opentelemetry-collector-releases/issues/412
